#!/usr/bin/env python3
"""Regenerate third_party/manami/mal_anilist_map.cpp from a manami
anime-offline-database release.

    tools/gen_idmap.py anime-offline-database.jsonl.zst --release 2026-27

Streams the line-delimited file (through `zstd -dc` for .zst) so the 60 MB
dataset never sits in memory at once. One entry per line; an entry maps to a
(mal_id, anilist_id) pair when its `sources` carry both a myanimelist.net
and an anilist.co anime URL. The rare entry that lists several ids of one
kind contributes the smallest of each (stable, and matches how the sites
themselves merge duplicates). The output is sorted by MAL id and unique in
both columns; the script refuses to write a table that isn't.

Dataset license: ODbL-1.0 (see third_party/manami/README).
"""

import argparse
import json
import re
import subprocess
import sys

MAL = re.compile(r"https://myanimelist\.net/anime/(\d+)")
ANILIST = re.compile(r"https://anilist\.co/anime/(\d+)")


def read_lines(path):
    if path.endswith(".zst"):
        proc = subprocess.Popen(["zstd", "-dc", path], stdout=subprocess.PIPE)
        for line in proc.stdout:
            yield line.decode("utf-8", "replace")
        proc.wait()
        if proc.returncode != 0:
            sys.exit(f"zstd failed with {proc.returncode}")
    else:
        with open(path, encoding="utf-8") as f:
            yield from f


def collect(path):
    pairs = []
    last_update = ""
    for line in read_lines(path):
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if "lastUpdate" in entry and not last_update:
            last_update = str(entry["lastUpdate"])
        sources = entry.get("sources")
        if not isinstance(sources, list):
            continue
        mal = [int(m.group(1)) for s in sources for m in [MAL.search(s)] if m]
        ani = [int(m.group(1)) for s in sources for m in [ANILIST.search(s)] if m]
        if mal and ani:
            pairs.append((min(mal), min(ani)))
    pairs.sort()
    return pairs, last_update


def check_unique(pairs):
    mal_ids = [p[0] for p in pairs]
    ani_ids = [p[1] for p in pairs]
    if len(set(mal_ids)) != len(pairs):
        sys.exit("duplicate MAL ids in the extracted table")
    if len(set(ani_ids)) != len(pairs):
        sys.exit("duplicate AniList ids in the extracted table")
    for m, a in pairs:
        if not (0 < m < 2**32 and 0 < a < 2**32):
            sys.exit(f"id out of uint32 range: {m} {a}")


def emit(pairs, release, last_update, out):
    lines = []
    lines.append("// GENERATED by tools/gen_idmap.py — do not edit by hand.")
    lines.append(f"// Source: manami-project/anime-offline-database release {release}"
                 + (f" (lastUpdate {last_update})" if last_update else "") + ".")
    lines.append("// Data license: ODbL-1.0 (https://opendatacommons.org/licenses/odbl/1-0/).")
    lines.append("// This table is a derivative database of that dataset; see")
    lines.append("// third_party/manami/README for attribution.")
    lines.append("")
    lines.append('#include "idmap.hpp"')
    lines.append("")
    lines.append("namespace shigoku::idmap::data {")
    lines.append("")
    lines.append(f'const char* const kRelease = "{release}";')
    lines.append(f"const std::size_t kCount = {len(pairs)};")
    lines.append("")
    lines.append("// (mal_id, anilist_id), sorted by mal_id.")
    lines.append("const std::uint32_t kByMal[] = {")
    per_line = 8
    for i in range(0, len(pairs), per_line):
        chunk = pairs[i:i + per_line]
        lines.append("  " + " ".join(f"{m},{a}," for m, a in chunk))
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace shigoku::idmap::data")
    lines.append("")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dataset", help="anime-offline-database.jsonl[.zst]")
    ap.add_argument("--release", required=True, help="upstream release tag, e.g. 2026-27")
    ap.add_argument("--out", default="third_party/manami/mal_anilist_map.cpp")
    args = ap.parse_args()

    pairs, last_update = collect(args.dataset)
    if not pairs:
        sys.exit("no (mal, anilist) pairs found — wrong file?")
    check_unique(pairs)
    emit(pairs, args.release, last_update, args.out)
    print(f"{len(pairs)} pairs -> {args.out}")


if __name__ == "__main__":
    main()
